### ISSUE TITLE
RejectedExecutionException on CallbackListener for RPC event propagation on shutdown

### ISSUE THREAD

**Issue by Cydhra** [KiBiSiK/Acromantula#12]
When the workspace shuts down, an `RejectedExecutionException` is thrown by the `CallbackListener` that is supposed to propagate Events to gRPC clients. This is probably not a critical bug, as so far it has only been observed when the workspace is shut down. Maybe this happens, because events are still waiting to be read by the RPC client while the channel is closed.

The bug results in an exception thrown while workspace shutdown:

```
Dec 28, 2020 1:03:19 PM com.google.common.util.concurrent.AbstractFuture executeListener
SEVERE: RuntimeException while executing runnable CallbackListener{net.cydhra.acromantula.pool.WorkerPool$launchTask$1@64dd089e} with executor com.google.common.util.concurrent.MoreExecutors$ListeningDecorator@58cbab43
java.util.concurrent.RejectedExecutionException: Task CallbackListener{net.cydhra.acromantula.pool.WorkerPool$launchTask$1@64dd089e} rejected from java.util.concurrent.ThreadPoolExecutor@7dfac41b[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:525)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1176)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.afterRanInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:133)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

A graceful way of shutting down the event queue should be found

**Comment by Cydhra** [comment]
I don't remember when, but I fixed that a long time ago
